import Head from "next/head";
import Nav from "../components/user/Nav";
import Script from "next/script";
import Link from "next/dist/client/link";
import { useRouter } from "next/router";
import kode from "./user/[kode]";

export default function Home() {
  const kue = [
    { kode: "101", nama: "Kue Tart" },
    { kode: "102", nama: "Kue Brownis" },
    { kode: "103", nama: "Kue Pasar" },
  ];
  const router = useRouter();
  const sendParamRouter = (kode) => {
    router.push(`/user/${kode}`);
  };
  return (
    <div className={"container"}>
      <Nav />
      <Head>
        <title>Aplikasi Next JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello Next</h1>
        <h3>Daftar Kue</h3>
        <ul>
          {kue.map((kue, idx) => (
            <>
              <li key={idx}>
                <Link href={`/user/${kue.kode}`}>
                  <a> {kue.kode}</a>
                </Link>
                <p>{kue.nama}</p>
                <button className="btn btn-primary" onClick={(e) => sendParamRouter(kue.kode)}>
                  Cek Jumlah
                </button>
              </li>
            </>
          ))}
        </ul>
      </main>

      <footer>
        <h4>Footer</h4>
      </footer>
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></Script>
    </div>
  );
}
